services:
    sharepai.share.listener:
        class: sharepai\share\event\listener
        arguments:
            - '@template'
            - '@config'
            - '@user'
            - '%core.php_ext%'
        tags:
            - { name: event.listener }
